name: build
on: push
jobs:
  build:  # the name of the job_id. labeled 'build'
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps: 
      - name: my first step
        env:
          MY_VAR: Hi. My name is 
          FNAME: Meeks
          MNAME: Mar
          LNAME: Tuck
        run: echo $MY_VAR $FNAME $MNAME $LNAME
      - name: My second step
        if: success()
        run: echo "The previous step has finished successfully"
      - name: My third step
        uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/ # if your publishing your package to npm or github package repo
      - name: my fourth step
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users'' first issue'
        pr-message: 'Message that will be displayed on users'' first pr'
