name: build
on: push
jobs:
  build:  # the name of the job_id. labeled 'build'
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12, 14]
    steps: 
      - name: my first step
        env:
          MY_VAR = Hi. My name is 
          FNAME = Meeks
          MNAME = Mar
          LNAME = Tuck
        run: echo $MY_VAR $FNAME $MNAME $LNAME
