name: build
on: push
jobs:
  build:  # the name of the job_id. labeled 'build'
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
    steps: 
      - name: my first step
        env:
          MY_VAR: Hi. My name is 
          FNAME: Meeks
          MNAME: Mar
          LNAME: Tuck
        run: echo $MY_VAR $FNAME $MNAME $LNAME
      - name: My second step
        if: success()
        run: echo "The previous step has finished successfully"
      - name: My third step send email
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result
          # Literal body:
          body: Build job of ${{github.repository}} completed successfully!
          # Read file contents as body:
          body: file://README.md
          to: tamicamtucker@gmail.com, tmarinatucker@gmail.com
          from: Meeks # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
          # Optional attachments:
          attachments: attachments.zip,git.diff,./dist/static/main.js
